name: ☔ Codecov

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write # To allow Codecov to comment on PRs

env:
  # @see https://typicode.github.io/husky/how-to.html#ci-server-and-docker
  HUSKY: 0

jobs:
  codecov:
    name: ☔ Coverage
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: ⎔ Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc

      - name: 📥 Download dependencies
        uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # v1.12.1

      - name: 🪣 Collect coverage
        run: npm --workspace=remeda run test:coverage

      - name: 🗺️ Upload coverage
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
