name: 📝 Lint PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: 🪧 Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: 📐 Conventional commit format
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        with:
          # see @semantic-release/commit-analyzer for semantics
          types: |
            fix
            feat 
            docs
            chore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required by the action

